### ISSUE TITLE
Image styling

### ISSUE THREAD

**Issue by akshitadixit** [GDSC-IIIT-Kalyani/hacktober-leaderboard#33]
![Screenshot from 2021-10-30 10-53-18](https://user-images.githubusercontent.com/56997545/139521395-7b45e61f-a2f4-4d78-b5f7-21bd088fa63e.png)

If you see the top 3 images should be all squares, but the 3rd one seems to be round.

**Comment by aabhas-sao** [comment]
hey @akshitadixit can i work on this.

**Comment by akshitadixit** [comment]
@aabhas-sao sure

**Comment by aabhas-sao** [comment]
@akshitadixit not able to run the project even after following readme and putting token in env file.

**Comment by aabhas-sao** [comment]
That image is circular (cropped) itself, it is not due some error in code see the source of that image.
